# Generated by Django 3.1.2 on 2020-10-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
