# Generated by Django 3.1.2 on 2020-10-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='lat',
            field=models.DecimalField(decimal_places=9, default=30, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='long',
            field=models.DecimalField(decimal_places=9, default=30, max_digits=20),
            preserve_default=False,
        ),
    ]
