# Generated by Django 3.1.2 on 2020-10-07 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.CharField(default='https://moonvillageassociation.org/wp-content/uploads/2018/06/default-profile-picture1.jpg', max_length=500),
        ),
    ]
