# Generated by Django 3.1.2 on 2020-10-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='current_city',
            field=models.CharField(default='Hometown, USA', max_length=50),
        ),
    ]
