# Generated by Django 3.1.2 on 2020-10-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20201009_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='static/default.jpg', null=True, upload_to='images/', verbose_name=''),
        ),
    ]
