# Generated by Django 3.1.2 on 2020-10-10 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_city_country'),
        ('main_app', '0006_auto_20201009_2155'),
    ]

    operations = [
    ]
